services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: blog
    volumes:
      - db:/var/lib/postgresql/blog/data/




  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
volumes:
  db: